#!/usr/bin/env python3
# Copyright (C) 2025 OETIKER+PARTNER AG - License: GNU General Public License v2

"""
Special agent for ISAM alarm status.
Fetches alarm data from a collector web service via HTTP GET.
"""

import sys
import requests
from cmk.utils.password_store import replace_passwords


def main(argv=None):
    replace_passwords()
    args = argv or sys.argv[1:]
    if len(args) != 1:
        sys.stderr.write("Usage: agent_oposs_isam_alarm URL\n")
        return 1
    response = requests.get(args[0], timeout=30)
    response.raise_for_status()
    sys.stdout.write(response.text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
