[package]
# Package Information
name = oposs_isam_alarm
title = OPOSS ISAM Alarm Status
author = Tobias Oetiker <tobi@oetiker.ch>
description = This check monitors ISAM alarm status via a collector web service.

    It fetches alarm data from a collector endpoint and reports alarm states
    for each discovered service.

# CheckMK Compatibility
version.min_required = 2.3.0p1
version.packaged = 2.3.0p34

# Optional
download_url = https://github.com/oposs/cmk-oposs_isam_alarm
version.usable_until =

# Build Options
validate_python = true
